---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-db-init-secret
stringData:
  my_initdb_script.sql: |
    CREATE USER supabase_admin LOGIN CREATEROLE CREATEDB REPLICATION BYPASSRLS;
    CREATE USER supabase_auth_admin NOINHERIT CREATEROLE LOGIN NOREPLICATION PASSWORD 'root';
    CREATE SCHEMA IF NOT EXISTS {{ .Values.gotrue.database.namespace }} AUTHORIZATION supabase_auth_admin;
    GRANT CREATE ON DATABASE postgres TO supabase_auth_admin;
    ALTER USER supabase_auth_admin SET search_path = '{{ .Values.gotrue.database.namespace }}';
