{{- if not .Values.gotrue.smtp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-smtp-secret
data:
  # smtp config
  GOTRUE_SMTP_HOST: {{ .Values.gotrue.smtp.host | b64enc | quote }}
  GOTRUE_SMTP_PORT: {{ .Values.gotrue.smtp.port | b64enc | quote }}
  GOTRUE_SMTP_USER: {{ .Values.gotrue.smtp.user | b64enc | quote }}
  GOTRUE_SMTP_PASS: {{ .Values.gotrue.smtp.password | b64enc | quote }}
  GOTRUE_SMTP_ADMIN_EMAIL: {{ .Values.gotrue.smtp.adminEmail | b64enc | quote }}
  GOTRUE_SMTP_MAX_FREQUENCY: {{ .Values.gotrue.smtp.maxFrequency | b64enc | quote }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-mailer-secret
data:
  # mailer config
  {{- if .Values.gotrue.mailer.secureEmailChangeEnabled }}
  GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: {{ "false" | b64enc | quote }}
  {{- end }}
  GOTRUE_MAILER_URLPATHS_CONFIRMATION: {{ .Values.gotrue.mailer.urlPaths.confirmation | b64enc | quote }}
  GOTRUE_MAILER_URLPATHS_INVITE: {{ .Values.gotrue.mailer.urlPaths.invite | b64enc | quote }}
  GOTRUE_MAILER_URLPATHS_RECOVERY: {{ .Values.gotrue.mailer.urlPaths.recovery | b64enc | quote }}
  GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: {{ .Values.gotrue.mailer.urlPaths.emailChange | b64enc | quote }}
  {{- if .Values.gotrue.mailer.autoConfirm }}
  GOTRUE_MAILER_AUTOCONFIRM: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_MAILER_AUTOCONFIRM: {{ "false" | b64enc | quote }}
  {{- end }}
  GOTRUE_MAILER_SUBJECTS_CONFIRMATION: {{ .Values.gotrue.mailer.subjects.confirmation | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_INVITE: {{ .Values.gotrue.mailer.subjects.invite | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_RECOVERY: {{ .Values.gotrue.mailer.subjects.recovery | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_EMAIL_CHANGE: {{ .Values.gotrue.mailer.subjects.emailChange | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_MAGIC_LINK: {{ .Values.gotrue.mailer.subjects.magicLink | b64enc | quote }}
