{{- if not .Values.gotrue.jwt.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-jwt-secret
data:
  {{- if not .Values.gotrue.jwt.secret }}
  jwtSecret: {{ randAlpha 32 | b64enc | quote }}
  {{- else }}
  jwtSecret: {{ .Values.gotrue.jwt.secret | b64enc | quote }}
  {{- end }}
{{- end }}
