{{- if not .Values.gotrue.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-gotrue-secret
data:
  GOTRUE_SITE_URL: {{ .Values.gotrue.siteUrl }}
  # adjust restrict if necessary
  URI_ALLOW_LIST: {{ .Values.gotrue.uriAllowList }}
  GOTRUE_JWT_SECRET: {{ .Values.gotrue.jwtSecret }}
  API_EXTERNAL_URL: {{ .Values.API_EXTERNAL_URL }}
  PORT: {{ .Values.gotrue.port }}
  GOTRUE_DB_DRIVER: {{ .Values.gotrue.database.driver }}
  DATABASE_URL: {{ .Values.gotrue.database.connectionUrl }}
  # smtp config
  GOTRUE_SMTP_HOST: {{ .Values.gotrue.smtp.host }}
  GOTRUE_SMTP_PORT: {{ .Values.gotrue.smtp.port }}
  GOTRUE_SMTP_USER: {{ .Values.gotrue.smtp.user }}
  GOTRUE_SMTP_PASS: {{ .Values.gotrue.smtp.password }}
  GOTRUE_SMTP_ADMIN_EMAIL: {{ .Values.gotrue.smtp.adminEmail }}
  GOTRUE_SMTP_MAX_FREQUENCY: {{ .Values.gotrue.smtp.maxFrequency }}
  GOTRUE_MAILER_URLPATHS_CONFIRMATION: {{ .Values.gotrue.mailer.urlPaths.confirmation }}
  GOTRUE_MAILER_URLPATHS_INVITE: {{ .Values.gotrue.mailer.urlPaths.invite }}
  GOTRUE_MAILER_URLPATHS_RECOVERY: {{ .Values.gotrue.mailer.urlPaths.recovery }}
  GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: {{ .Values.gotrue.mailer.urlPaths.emailChange }}
  GOTRUE_MAILER_AUTOCONFIRM: {{ .Values.gotrue.mailer.autoConfirm }}
  # Google OAuth config
  {{- if .Values.gotrue.external.google.enabled }}
  GOTRUE_EXTERNAL_GOOGLE_ENABLED: {{ .Values.gotrue.external.google.enabled }}
  GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: {{ .Values.gotrue.external.google.clientId }}
  GOTRUE_EXTERNAL_GOOGLE_SECRET: {{ .Values.gotrue.external.google.secret }}
  GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: {{ .Values.gotrue.external.google.redirectUri }}
  {{- end }}
  # GITHUB OAuth config
  {{- if .Values.gotrue.external.github.enabled }}
  GOTRUE_EXTERNAL_GITHUB_ENABLED: {{ .Values.gotrue.external.github.enabled }}
  GOTRUE_EXTERNAL_GITHUB_CLIENT_ID: {{ .Values.gotrue.external.github.clientId }}
  GOTRUE_EXTERNAL_GITHUB_SECRET: {{ .Values.gotrue.external.github.secret }}
  GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI: {{ .Values.gotrue.external.github.redirectUri }}
  {{- end }}
  # Discord OAuth config
  {{- if .Values.gotrue.external.discord.enabled }}
  GOTRUE_EXTERNAL_DISCORD_ENABLED: {{ .Values.gotrue.external.discord.enabled }}
  GOTRUE_EXTERNAL_DISCORD_CLIENT_ID: {{ .Values.gotrue.external.discord.clientId }}
  GOTRUE_EXTERNAL_DISCORD_SECRET: {{ .Values.gotrue.external.discord.secret }}
  GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI: {{ .Values.gotrue.external.discord.redirectUri }}
  {{- end }}
  # SAML config
  {{- if .Values.gotrue.external.saml.enabled }}
  GOTRUE_EXTERNAL_SAML_ENABLED: {{ .Values.gotrue.external.saml.enabled }}
  GOTRUE_EXTERNAL_SAML_METADATA_URL: {{ .Values.gotrue.external.saml.metadataUrl }}
  GOTRUE_EXTERNAL_SAML_API_BASE: {{ .Values.gotrue.external.saml.apiBase }}
  GOTRUE_EXTERNAL_SAML_NAME: {{ .Values.gotrue.external.saml.name }}
  GOTRUE_EXTERNAL_SAML_SIGNING_CERT: {{ .Values.gotrue.external.saml.signingCert }}
  GOTRUE_EXTERNAL_SAML_SIGNING_KEY: {{ .Values.gotrue.external.saml.signingKey }}
  {{- end }}
  # Prometheus Metrics
  GOTRUE_METRICS_ENABLED: {{ .Values.gotrue.metrics.enabled }}
  GOTRUE_METRICS_EXPORTER: {{ .Values.gotrue.metrics.exporter }}
{{- end }}
