{{- if not .Values.gotrue.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-secret
data:
  # database
  GOTRUE_DB_DRIVER: {{ .Values.gotrue.database.driver | b64enc | quote }}
  DB_NAMESPACE: {{ .Values.gotrue.database.namespace | b64enc | quote }}
  {{- if .Values.gotrue.database.databaseUrl }}
  DATABASE_URL: {{ .Values.gotrue.database.databaseUrl | b64enc | quote }}
  {{- else if .Values.gotrue.database.password }}
  DATABASE_URL: {{- printf "%s://%s:%s@%s:%s/%s" .Values.gotrue.database.driver .Values.gotrue.database.user .Values.gotrue.database.password .Values.gotrue.database.host .Values.gotrue.database.port .Values.gotrue.database.database | b64enc | quote }}
  {{- else if .Values.gotrue.database.sslmode }}
  DATABASE_URL: {{- printf "%s://%s@%s:%s/%s;sslmode=%s;sslrootcert=%s;sslcert=%s;sslkey=%s" .Values.gotrue.database.driver .Values.gotrue.database.user .Values.gotrue.database.host .Values.gotrue.database.port .Values.gotrue.database.database .Values.gotrue.database.sslmode .Values.gotrue.database.sslRootCert .Values.gotrue.database.sslCert .Values.gotrue.database.sslKey | b64enc | quote }}
  {{- end }} 
{{- end }}
