{{- if not .Values.gotrue.external.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-external-auth
data:
  # Google OAuth config
  {{- if .Values.gotrue.external.google.enabled }}
  GOTRUE_EXTERNAL_GOOGLE_ENABLED: {{ .Values.gotrue.external.google.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: {{ .Values.gotrue.external.google.clientId | b64enc | quote }}
  GOTRUE_EXTERNAL_GOOGLE_SECRET: {{ .Values.gotrue.external.google.secret | b64enc | quote }}
  GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: {{ .Values.gotrue.external.google.redirectUri | b64enc | quote }}
  {{- end }}
  # GITHUB OAuth config
  {{- if .Values.gotrue.external.github.enabled }}
  GOTRUE_EXTERNAL_GITHUB_ENABLED: {{ .Values.gotrue.external.github.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_GITHUB_CLIENT_ID: {{ .Values.gotrue.external.github.clientId | b64enc | quote }}
  GOTRUE_EXTERNAL_GITHUB_SECRET: {{ .Values.gotrue.external.github.secret | b64enc | quote }}
  GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI: {{ .Values.gotrue.external.github.redirectUri | b64enc | quote }}
  {{- end }}
  # Discord OAuth config
  {{- if .Values.gotrue.external.discord.enabled }}
  GOTRUE_EXTERNAL_DISCORD_ENABLED: {{ .Values.gotrue.external.discord.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_DISCORD_CLIENT_ID: {{ .Values.gotrue.external.discord.clientId | b64enc | quote }}
  GOTRUE_EXTERNAL_DISCORD_SECRET: {{ .Values.gotrue.external.discord.secret | b64enc | quote }}
  GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI: {{ .Values.gotrue.external.discord.redirectUri | b64enc | quote }}
  {{- end }}
  # SAML config
  {{- if .Values.gotrue.external.saml.enabled }}
  GOTRUE_EXTERNAL_SAML_ENABLED: {{ .Values.gotrue.external.saml.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_METADATA_URL: {{ .Values.gotrue.external.saml.metadataUrl | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_API_BASE: {{ .Values.gotrue.external.saml.apiBase | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_NAME: {{ .Values.gotrue.external.saml.name | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_SIGNING_CERT: {{ .Values.gotrue.external.saml.signingCert | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_SIGNING_KEY: {{ .Values.gotrue.external.saml.signingKey | b64enc | quote }}
  {{- end }}
{{- end }}
