{{- if not .Values.gotrue.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-secret
data:
  GOTRUE_SITE_URL: {{ .Values.gotrue.siteUrl | b64enc | quote }}
  # adjust restrict if necessary
  GOTRUE_URI_ALLOW_LIST: {{ .Values.gotrue.uriAllowList | b64enc | quote }}
  API_EXTERNAL_URL: {{ .Values.gotrue.externalUrl | b64enc | quote }}
  PORT: {{ .Values.gotrue.port | b64enc | quote }}
  # database
  GOTRUE_DB_DRIVER: {{ .Values.gotrue.database.driver | b64enc | quote }}
  DATABASE_URL: {{ .Values.gotrue.database.connectionUrl | b64enc | quote }}
  DB_NAMESPACE: {{ .Values.gotrue.database.namespace | b64enc | quote }}
  # jwt config
  {{- if not .Values.gotrue.jwt.secret }}
  GOTRUE_JWT_SECRET: {{ randAlpha 32 | b64enc | quote }}
  {{- else }}
  GOTRUE_JWT_SECRET: {{ .Values.gotrue.jwt.secret | b64enc | quote }}
  {{- end }}
  GOTRUE_JWT_EXP: {{ .Values.gotrue.jwt.exp | b64enc | quote }}
  GOTRUE_JWT_AUD: {{ .Values.gotrue.jwt.aud | b64enc | quote }}
  GOTRUE_JWT_DEFAULT_GROUP_NAME: {{ .Values.gotrue.jwt.defaultGroupName | b64enc | quote }}
  GOTRUE_JWT_ADMIN_ROLES: {{ .Values.gotrue.jwt.adminRoles | b64enc | quote }}
  # signups
  {{- if .Values.gotrue.signup.disable }}
  GOTRUE_DISABLE_SIGNUP: {{ "true" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.external.email.enabled }}
  GOTRUE_EXTERNAL_EMAIL_ENABLED: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_EXTERNAL_EMAIL_ENABLED: {{ "false" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.external.phone.enabled }}
  GOTRUE_EXTERNAL_PHONE_ENABLED: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_EXTERNAL_PHONE_ENABLED: {{ "false" | b64enc | quote }}
  {{- end }}
  GOTRUE_EXTERNAL_IOS_BUNDLE_ID: {{ .Values.gotrue.external.ios.bundleID | b64enc | quote }}
  # smtp config
  GOTRUE_SMTP_HOST: {{ .Values.gotrue.smtp.host | b64enc | quote }}
  GOTRUE_SMTP_PORT: {{ .Values.gotrue.smtp.port | b64enc | quote }}
  GOTRUE_SMTP_USER: {{ .Values.gotrue.smtp.user | b64enc | quote }}
  GOTRUE_SMTP_PASS: {{ .Values.gotrue.smtp.password | b64enc | quote }}
  GOTRUE_SMTP_ADMIN_EMAIL: {{ .Values.gotrue.smtp.adminEmail | b64enc | quote }}
  GOTRUE_SMTP_MAX_FREQUENCY: {{ .Values.gotrue.smtp.maxFrequency | b64enc | quote }}
  # mailer config
  {{- if .Values.gotrue.mailer.secureEmailChangeEnabled }}
  GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: {{ "false" | b64enc | quote }}
  {{- end }}
  GOTRUE_MAILER_URLPATHS_CONFIRMATION: {{ .Values.gotrue.mailer.urlPaths.confirmation | b64enc | quote }}
  GOTRUE_MAILER_URLPATHS_INVITE: {{ .Values.gotrue.mailer.urlPaths.invite | b64enc | quote }}
  GOTRUE_MAILER_URLPATHS_RECOVERY: {{ .Values.gotrue.mailer.urlPaths.recovery | b64enc | quote }}
  GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: {{ .Values.gotrue.mailer.urlPaths.emailChange | b64enc | quote }}
  {{- if .Values.gotrue.mailer.autoConfirm }}
  GOTRUE_MAILER_AUTOCONFIRM: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_MAILER_AUTOCONFIRM: {{ "false" | b64enc | quote }}
  {{- end }}
  GOTRUE_MAILER_SUBJECTS_CONFIRMATION: {{ .Values.gotrue.mailer.subjects.confirmation | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_INVITE: {{ .Values.gotrue.mailer.subjects.invite | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_RECOVERY: {{ .Values.gotrue.mailer.subjects.recovery | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_EMAIL_CHANGE: {{ .Values.gotrue.mailer.subjects.emailChange | b64enc | quote }}
  GOTRUE_MAILER_SUBJECTS_MAGIC_LINK: {{ .Values.gotrue.mailer.subjects.magicLink | b64enc | quote }}
  # security config
  {{- if .Values.gotrue.security.refreshToken.rotationEnabled }}
  GOTRUE_SECURITY_REFRESH_TOKEN_ROTATION_ENABLED: {{ "true" | b64enc | quote }}
  GOTRUE_SECURITY_REFRESH_TOKEN_REUSE_INTERVAL: {{ .Values.gotrue.security.refreshToken.reuseInterval | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.security.updatePasswordRequireReauth }}
  GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTH: {{ "true" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.security.captcha.enabled }}
  GOTRUE_SECURITY_CAPTCHA_ENABLED: {{ "true" | b64enc | quote }}
  GOTRUE_SECURITY_CAPTCHA_PROVIDER: {{ .Values.gotrue.security.captcha.provider }}
  GOTRUE_SECURITY_CAPTCHA_SECRET: {{ .Values.gotrue.security.captcha.secret }}
  GOTRUE_SECURITY_CAPTCHA_TIMEOUT: {{ .Values.gotrue.security.captcha.timeout }}
  GOTRUE_SECURITY_CAPTCHA_SESSION_KEY: {{ .Values.gotrue.security.captcha.sessionKey }}
  {{- end }}
  # Google OAuth config
  {{- if .Values.gotrue.external.google.enabled }}
  GOTRUE_EXTERNAL_GOOGLE_ENABLED: {{ .Values.gotrue.external.google.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: {{ .Values.gotrue.external.google.clientId | b64enc | quote }}
  GOTRUE_EXTERNAL_GOOGLE_SECRET: {{ .Values.gotrue.external.google.secret | b64enc | quote }}
  GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: {{ .Values.gotrue.external.google.redirectUri | b64enc | quote }}
  {{- end }}
  # GITHUB OAuth config
  {{- if .Values.gotrue.external.github.enabled }}
  GOTRUE_EXTERNAL_GITHUB_ENABLED: {{ .Values.gotrue.external.github.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_GITHUB_CLIENT_ID: {{ .Values.gotrue.external.github.clientId | b64enc | quote }}
  GOTRUE_EXTERNAL_GITHUB_SECRET: {{ .Values.gotrue.external.github.secret | b64enc | quote }}
  GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI: {{ .Values.gotrue.external.github.redirectUri | b64enc | quote }}
  {{- end }}
  # Discord OAuth config
  {{- if .Values.gotrue.external.discord.enabled }}
  GOTRUE_EXTERNAL_DISCORD_ENABLED: {{ .Values.gotrue.external.discord.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_DISCORD_CLIENT_ID: {{ .Values.gotrue.external.discord.clientId | b64enc | quote }}
  GOTRUE_EXTERNAL_DISCORD_SECRET: {{ .Values.gotrue.external.discord.secret | b64enc | quote }}
  GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI: {{ .Values.gotrue.external.discord.redirectUri | b64enc | quote }}
  {{- end }}
  # SAML config
  {{- if .Values.gotrue.external.saml.enabled }}
  GOTRUE_EXTERNAL_SAML_ENABLED: {{ .Values.gotrue.external.saml.enabled | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_METADATA_URL: {{ .Values.gotrue.external.saml.metadataUrl | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_API_BASE: {{ .Values.gotrue.external.saml.apiBase | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_NAME: {{ .Values.gotrue.external.saml.name | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_SIGNING_CERT: {{ .Values.gotrue.external.saml.signingCert | b64enc | quote }}
  GOTRUE_EXTERNAL_SAML_SIGNING_KEY: {{ .Values.gotrue.external.saml.signingKey | b64enc | quote }}
  {{- end }}
{{- end }}
