{{- if not .Values.gotrue.jwt.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-secret
data:
  # jwt config
  {{- if not .Values.gotrue.jwt.secret }}
  GOTRUE_JWT_SECRET: {{ randAlpha 32 | b64enc | quote }}
  {{- else }}
  GOTRUE_JWT_SECRET: {{ .Values.gotrue.jwt.secret | b64enc | quote }}
  {{- end }}
  GOTRUE_JWT_EXP: {{ .Values.gotrue.jwt.exp | b64enc | quote }}
  GOTRUE_JWT_AUD: {{ .Values.gotrue.jwt.aud | b64enc | quote }}
  GOTRUE_JWT_DEFAULT_GROUP_NAME: {{ .Values.gotrue.jwt.defaultGroupName | b64enc | quote }}
  GOTRUE_JWT_ADMIN_ROLES: {{ .Values.gotrue.jwt.adminRoles | b64enc | quote }}
{{- end }}
