{{- if not .Values.gotrue.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue-secret
data:
  GOTRUE_SITE_URL: {{ .Values.gotrue.siteUrl | b64enc | quote }}
  GOTRUE_URI_ALLOW_LIST: {{ .Values.gotrue.uriAllowList | b64enc | quote }}
  API_EXTERNAL_URL: {{ .Values.gotrue.externalUrl | b64enc | quote }}
  PORT: {{ .Values.gotrue.port | b64enc | quote }}
  # signups
  {{- if .Values.gotrue.signup.disable }}
  GOTRUE_DISABLE_SIGNUP: {{ "true" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.external.email.enabled }}
  GOTRUE_EXTERNAL_EMAIL_ENABLED: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_EXTERNAL_EMAIL_ENABLED: {{ "false" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.external.phone.enabled }}
  GOTRUE_EXTERNAL_PHONE_ENABLED: {{ "true" | b64enc | quote }}
  {{- else }}
  GOTRUE_EXTERNAL_PHONE_ENABLED: {{ "false" | b64enc | quote }}
  {{- end }}
  GOTRUE_EXTERNAL_IOS_BUNDLE_ID: {{ .Values.gotrue.external.ios.bundleID | b64enc | quote }}
  # security config
  {{- if .Values.gotrue.security.refreshToken.rotationEnabled }}
  GOTRUE_SECURITY_REFRESH_TOKEN_ROTATION_ENABLED: {{ "true" | b64enc | quote }}
  GOTRUE_SECURITY_REFRESH_TOKEN_REUSE_INTERVAL: {{ .Values.gotrue.security.refreshToken.reuseInterval | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.security.updatePasswordRequireReauth }}
  GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTH: {{ "true" | b64enc | quote }}
  {{- end }}
  {{- if .Values.gotrue.security.captcha.enabled }}
  GOTRUE_SECURITY_CAPTCHA_ENABLED: {{ "true" | b64enc | quote }}
  GOTRUE_SECURITY_CAPTCHA_PROVIDER: {{ .Values.gotrue.security.captcha.provider }}
  GOTRUE_SECURITY_CAPTCHA_SECRET: {{ .Values.gotrue.security.captcha.secret }}
  GOTRUE_SECURITY_CAPTCHA_TIMEOUT: {{ .Values.gotrue.security.captcha.timeout }}
  GOTRUE_SECURITY_CAPTCHA_SESSION_KEY: {{ .Values.gotrue.security.captcha.sessionKey }}
  {{- end }}
{{- end }}
